# hosts/lan/hacktop/atmons-color.nix
#
# Generates the KubeJS server script backing the player-facing /color command.
#
# Why this exists: FTB Ranks can format a player's name (the ftbranks.name_format
# node, see atmons-ranks.nix), but every /ftbranks subcommand requires operator
# level 4. So FTB Ranks alone can express "VIPs are gold" and cannot express
# "let a player choose". This script is the bridge: a level-0 command that
# performs the privileged rank change on the player's behalf.
#
# The combination list is passed in from atmons-ranks.nix, so the command's
# arguments and the ranks that back them are generated from one source and
# cannot drift.
#
# Injection safety: colour and style are Brigadier LITERAL subcommands, not
# string arguments. There is therefore no player-controlled text anywhere in the
# command strings this builds - the only interpolated value is the player's own
# name, which Mojang constrains to [A-Za-z0-9_]. That is deliberately stronger
# than validating a free-text argument, and it gets tab-completion for free.
#
# Note for whoever edits this: nix-minecraft's `files` copier runs the contents
# through awk to substitute @VAR@ placeholders from the service environment, so
# avoid stray at-sign pairs in this file. Minecraft format codes use '&', so
# this is a lint concern rather than a live problem.
{
  pkgs,
  lib,
  combos,
}:

let
  # Group by colour so the command reads /color <colour> [style], with the
  # plain variant on the bare colour literal.
  colourNames = lib.unique (map (c: c.colour) combos);

  plainRankOf =
    colour: (lib.findFirst (c: c.colour == colour && c.style == "plain") null combos).rank;

  styleLiterals =
    colour:
    lib.concatMapStrings (
      c: "          .then(Commands.literal('${c.style}').executes(ctx => setFormat(ctx, '${c.rank}')))\n"
    ) (builtins.filter (c: c.colour == colour && c.style != "plain") combos);

  colourLiterals = lib.concatMapStrings (colour: ''
    ${
      "      .then(Commands.literal('"
      + colour
      + "').executes(ctx => setFormat(ctx, '"
      + plainRankOf colour
      + "'))"
    }
    ${styleLiterals colour}      )
  '') colourNames;

  removeAll = lib.concatMapStrings (
    c: "  run(server, 'ftbranks remove ' + name + ' ${c.rank}')\n"
  ) combos;
in
pkgs.writeText "atmons_color.js" ''
  // Generated by hosts/lan/hacktop/atmons-color.nix - do not edit in place.
  // nix-minecraft re-copies kubejs/ from the store on every server start, so
  // edits made on the box are reverted at the next restart.

  // Loaded once, at top level, and NOT inside the function that uses it.
  // A `const` binding inside the repeatedly-invoked permission check made
  // KubeJS's Rhino throw "InternalError: TypeError: redeclaration of var api",
  // which - because the check fails closed - silently denied /color to
  // everyone, including players who really did hold the rank. Every script in
  // the pack loads its Java classes at top level; this now matches.
  const FTBRanksAPI = Java.loadClass('dev.ftb.mods.ftbranks.api.FTBRanksAPI')

  // Runs a command as the server console (permission level 4) with output
  // suppressed. Uses vanilla's dispatcher rather than a KubeJS helper so the
  // script does not depend on KubeJS wrapper specifics across versions.
  function run(server, command) {
    const source = server.createCommandSourceStack().withSuppressedOutput()
    server.getCommands().performPrefixedCommand(source, command)
  }

  // Fail closed: a command that internally escalates to console privileges
  // should deny rather than guess when it cannot resolve permissions. The node
  // currently sits on the `player` rank, so in practice everyone passes.
  function canRecolour(player) {
    try {
      return FTBRanksAPI.getPermissionValue(player, 'command.color').asBoolean().orElse(false)
    } catch (err) {
      console.error('[atmons-color] permission lookup failed, denying: ' + err)
      return false
    }
  }

  function setFormat(ctx, rank) {
    const player = ctx.source.player
    if (!player) {
      // Console and command blocks have no name to format.
      return 0
    }
    if (!canRecolour(player)) {
      player.tell(Text.red('You are not allowed to change your name colour.'))
      return 0
    }

    const server = ctx.source.server
    const name = player.username

    // Remove every format rank before adding one. Removing a rank the player is
    // not in is a no-op, and this prevents holding two ranks of equal power,
    // where which name_format wins would be undefined.
  ${removeAll}
    if (rank !== 'none') {
      run(server, 'ftbranks add ' + name + ' ' + rank)
      player.tell(Text.green('Name format updated.'))
    } else {
      player.tell(Text.green('Name format cleared.'))
    }
    return 1
  }

  ServerEvents.commandRegistry(event => {
    const { commands: Commands } = event
    event.register(
      Commands.literal('color')
        .then(Commands.literal('none').executes(ctx => setFormat(ctx, 'none')))
  ${colourLiterals}    )
  })
''
