# hosts/lan/hacktop/atmons-color.nix
#
# Generates the KubeJS server script backing the player-facing /color command.
#
# Why this exists: FTB Ranks can colour a player's name (the ftbranks.name_format
# node, see atmons-ranks.nix), but every /ftbranks subcommand requires operator
# level 4. So FTB Ranks alone can express "VIPs are gold" and cannot express
# "let a player choose their own colour". This script is the bridge: a level-0
# command that performs the privileged rank change on the player's behalf.
#
# The colour list is passed in from atmons-ranks.nix so the command's arguments
# and the ranks that back them are generated from one source and cannot drift.
#
# Injection safety: each colour is a Brigadier LITERAL subcommand, not a string
# argument. There is therefore no player-controlled text anywhere in the command
# strings this builds - the only interpolated value is the player's own name,
# which Mojang constrains to [A-Za-z0-9_]. This is deliberately stronger than
# validating a free-text argument, and it gets tab-completion for free.
#
# Note for whoever edits this: nix-minecraft's `files` copier runs the contents
# through awk to substitute @VAR@ placeholders from the service environment, so
# avoid stray at-sign pairs in this file. Minecraft colour codes use '&', so
# this is a lint concern rather than a live problem.
{
  pkgs,
  lib,
  colours,
}:

let
  # KubeJS parses this at server start; a syntax error here disables the script
  # and logs to the server console (now visible in journalctl, see minecraft.nix).
  #
  # Indentation is baked into these strings rather than written as indented Nix
  # strings: interpolating a multi-line block into an '' '' literal makes the
  # emitted indentation depend on Nix's common-prefix stripping, which silently
  # flattens it to column zero.
  colourLiterals = lib.concatMapStrings (
    c: "      .then(Commands.literal('${c.id}').executes(ctx => setColour(ctx, '${c.id}')))\n"
  ) colours;

  removeAll = lib.concatMapStrings (
    c: "  run(server, 'ftbranks remove ' + name + ' color_${c.id}')\n"
  ) colours;
in
pkgs.writeText "atmons_color.js" ''
  // Generated by hosts/lan/hacktop/atmons-color.nix - do not edit in place.
  // nix-minecraft re-copies kubejs/ from the store on every server start, so
  // edits made on the box are reverted at the next restart.

  // Runs a command as the server console (permission level 4) with output
  // suppressed. Uses vanilla's dispatcher rather than a KubeJS helper so the
  // script does not depend on KubeJS wrapper specifics across versions.
  function run(server, command) {
    const source = server.createCommandSourceStack().withSuppressedOutput()
    server.getCommands().performPrefixedCommand(source, command)
  }

  // Fail closed. If FTB Ranks is missing, renamed, or its API moves under a
  // pack update, nobody gets to recolour - which is the safe direction for a
  // command that escalates to console privileges internally.
  function canRecolour(player) {
    try {
      const api = Java.loadClass('dev.ftb.mods.ftbranks.api.FTBRanksAPI')
      return api.getPermissionValue(player, 'command.color').asBoolean().orElse(false)
    } catch (err) {
      console.error('[atmons-color] permission lookup failed, denying: ' + err)
      return false
    }
  }

  function setColour(ctx, colour) {
    const player = ctx.source.player
    if (!player) {
      // Console and command blocks have no name to colour.
      return 0
    }
    // Enforcement lives here rather than in .requires() so there is exactly one
    // permission check to reason about. The cost is that /color tab-completes
    // for everyone and then refuses, which is friendlier than a command that
    // silently does not exist.
    if (!canRecolour(player)) {
      player.tell(Text.red('You need the "trusted" rank to change your name colour.'))
      return 0
    }

    const server = ctx.source.server
    const name = player.username

    // Remove every colour rank before adding one. Removing a rank the player is
    // not in is a no-op, and this keeps a player from accumulating two colour
    // ranks of equal power, where which one wins would be undefined.
  ${removeAll}
    if (colour !== 'none') {
      run(server, 'ftbranks add ' + name + ' color_' + colour)
      player.tell(Text.green('Name colour set to ' + colour + '.'))
    } else {
      player.tell(Text.green('Name colour cleared.'))
    }
    return 1
  }

  ServerEvents.commandRegistry(event => {
    const { commands: Commands } = event
    event.register(
      Commands.literal('color')
        .then(Commands.literal('none').executes(ctx => setColour(ctx, 'none')))
  ${colourLiterals}    )
  })
''
